### ISSUE TITLE
mdat atoms not parsed when several mdat in the stream

### ISSUE THREAD

**Issue by jcdr428** [essential61/mp4analyser#23] opened 2021-01-18 21:22 UTC
Hi @essential61 , an interesting mp4 with several mdat atoms:
https://1drv.ms/v/s!AuYcZ0yHv3Dt5jQbgvK55jzqb9Fs?e=TuHvxl

None of the mdat boxes are parsed (message": "No samples found.")

**Comment by essential61** [comment] 2021-01-19 14:52
I'll have to add some additional logic to  _generate_samples_from_moov() in order to cover corner case of the entries in sample tables spanning multiple mdats

**Comment by jcdr428** [comment] 2021-01-29 19:50
Good work, thank you Steven !

**Comment by essential61** [comment] 2021-01-30 08:53
Looks like this now works with no regressions so I'll close the issue.

**Closed** 2021-01-30 13:52 UTC
